name: .NET

on:
  push:
    tags:
    - 'v*'
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: Get Version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Docker
      run: docker build -f $(pwd)/actionsnetdemo/Dockerfile . -t test:${{steps.get_version.outputs.VERSION}} -t test:latest

    - uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATEKEY }}
        port: ${{ secrets.PORT }}
        script: |
          docker stop test
          docker rm test
          docker run -p 5000:80 --name test -d test
          docker rmi 94a6b4:2d615e5b7dc14a75b7da53e65b7f21ab
          docker rmi 94a6b4:9bf4f3bf9f6745099c0d15ddc6bebe2b
          docker images --no-trunc | grep '<none>' | awk '{ print $3 }' | xargs -r docker rmi
          
